<?php

/*
 * This file is part of Pluf Framework, a simple PHP Application Framework.
 * Copyright (C) 2010-2020 Phoinex Scholars Co. (http://dpq.co.ir)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Defines a http response for robots.txt file. It renders content of robots.txt as response.
 * If robots.txt file does not exist, an empty string will be considered as rendered content of robots.txt.
 * 
 * It also adds some URLs as sitemap in the end of response content.
 *
 * @author hadi
 *        
 */
class Tenant_HTTP_Response_RobotsTxt extends Pluf_HTTP_Response
{

    public $filePath;

    private $host;

    function __construct($host, $filepath)
    {
        parent::__construct($filepath, 'text/plain');
        $this->filePath = $filepath;
        $this->host = $host;
    }

    /**
     *
     * {@inheritdoc}
     * @see Pluf_HTTP_Response::render()
     */
    function render($output_body = true)
    {
        $content = '';
        try {
            $content = file_get_contents($this->filePath);
        } catch (Exception $ex) {
            error_log($ex);
        }
        $content = $content . PHP_EOL . '# Automatically generated by Seen Server';
        $content = $content . PHP_EOL . 'Sitemap: ' . $this->host . '/seo/sitemap/sitemap.xml';
        $this->content = $content;
        parent::render($output_body);
    }
}
